### ISSUE TITLE
Package not available in MELPA 

### ISSUE THREAD

**Issue by lokithus** [emacs-pe/password-vault-#1]
Hi, it's good to see other peruvians using Emacs. I am a novice with Emacs and programming in general but after using a mix of Keepass and password-store for years I wanted to try using Emacs for saving my passwords. When I tried to install this package (that looks like an upgrade of password-vault),  I couldn't find it on MELPA (I am using standard MELPA not MELPA "stable"). Thanks and I hope this project keeps going on.

**Comment by PuercoPop** [comment]
> see other peruvians using Emacs

:wave: :peru: 

> Thanks and I hope this project keeps going on.

It does, at least I use it every day.

> I couldn't find it on MELPA 

That's because I never got around to submitted this version version to MELPA so its not there. And to submit it I would have to change the license from 'Copyheart' to GPLv3+ which I don't feel like doing.

But it is in the emacs-pe package archive which you can add use `(add-to-list 'package-archives (emacs-pe '(("emacs-pe" . "https://emacs-pe.github.io/packages"))) t)`. Although you can clone it and load with something like

```
(use-package password-vault+
  :load-path "site-lisp/password-vault+"
  :config (password-vault+-register-secrets-file (substitute-in-file-name "$HOME/.emacs.d/passwords.el.gpg")))
```

If I ever get around to integrating it with auth-source and porting it to ivy (This is the only package I use that uses helm) I'd submit to MELPA, it seems unlikely as it scratches my itch in its current incantation.

If you already use [password-store](https://www.passwordstore.org/) I recommend you try either. Both are written by prolific elispers. Damien Cassou tends to build well thought out UIs in particular.

- https://github.com/NicolasPetton/pass
- https://github.com/DamienCassou/auth-password-store

**Comment by lokithus** [comment]
I guess I will try password-vault+ and use it as a way to learn and practice elisp. I didn't realize there was an "official" password-store extension for Emacs. I like password-vault+ because its integration with Helm (I use it too). Thanks again,  I will copy and try it.

**Comment by PuercoPop** [comment]
Let me know if you run into any issue
